# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: hello_bili.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10hello_bili.proto\x12\x04test\"*\n\rHelloDeweiReq\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0b\n\x03\x61ge\x18\x02 \x01(\x05\"!\n\x0fHelloDeweiReply\x12\x0e\n\x06result\x18\x01 \x01(\t\"\x9f\x02\n\x10HelloTestRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0b\n\x03\x61ge\x18\x02 \x01(\x03\x12\x0c\n\x04\x64\x61ta\x18\x03 \x03(\t\x12\x32\n\x06number\x18\x04 \x03(\x0b\x32\".test.HelloTestRequest.NumberEntry\x1aK\n\x1bHelloTestRequestNumberValue\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0b\n\x03\x61ge\x18\x02 \x01(\x05\x12\x11\n\tis_active\x18\x03 \x01(\x08\x1a\x61\n\x0bNumberEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x41\n\x05value\x18\x02 \x01(\x0b\x32\x32.test.HelloTestRequest.HelloTestRequestNumberValue:\x02\x38\x01\"\x13\n\x11HelloTestResponse\"+\n\x1bTestClientRecvStreamRequest\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\t\".\n\x1cTestClientRecvStreamResponse\x12\x0e\n\x06result\x18\x01 \x01(\t\"+\n\x1bTestClientSendStreamRequest\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\t\".\n\x1cTestClientSendStreamResponse\x12\x0e\n\x06result\x18\x01 \x01(\t\"\'\n\x17TestTwoWayStreamRequest\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\t\"*\n\x18TestTwoWayStreamResponse\x12\x0e\n\x06result\x18\x01 \x01(\t2\xa5\x03\n\x04\x42ili\x12:\n\nHelloDewei\x12\x13.test.HelloDeweiReq\x1a\x15.test.HelloDeweiReply\"\x00\x12\x42\n\tHelloTest\x12\x16.test.HelloTestRequest\x1a\x17.test.HelloTestResponse\"\x00(\x01\x30\x01\x12\x61\n\x14TestClientRecvStream\x12!.test.TestClientRecvStreamRequest\x1a\".test.TestClientRecvStreamResponse\"\x00\x30\x01\x12\x61\n\x14TestClientSendStream\x12!.test.TestClientSendStreamRequest\x1a\".test.TestClientSendStreamResponse\"\x00(\x01\x12W\n\x10TestTwoWayStream\x12\x1d.test.TestTwoWayStreamRequest\x1a\x1e.test.TestTwoWayStreamResponse\"\x00(\x01\x30\x01\x62\x06proto3')



_HELLODEWEIREQ = DESCRIPTOR.message_types_by_name['HelloDeweiReq']
_HELLODEWEIREPLY = DESCRIPTOR.message_types_by_name['HelloDeweiReply']
_HELLOTESTREQUEST = DESCRIPTOR.message_types_by_name['HelloTestRequest']
_HELLOTESTREQUEST_HELLOTESTREQUESTNUMBERVALUE = _HELLOTESTREQUEST.nested_types_by_name['HelloTestRequestNumberValue']
_HELLOTESTREQUEST_NUMBERENTRY = _HELLOTESTREQUEST.nested_types_by_name['NumberEntry']
_HELLOTESTRESPONSE = DESCRIPTOR.message_types_by_name['HelloTestResponse']
_TESTCLIENTRECVSTREAMREQUEST = DESCRIPTOR.message_types_by_name['TestClientRecvStreamRequest']
_TESTCLIENTRECVSTREAMRESPONSE = DESCRIPTOR.message_types_by_name['TestClientRecvStreamResponse']
_TESTCLIENTSENDSTREAMREQUEST = DESCRIPTOR.message_types_by_name['TestClientSendStreamRequest']
_TESTCLIENTSENDSTREAMRESPONSE = DESCRIPTOR.message_types_by_name['TestClientSendStreamResponse']
_TESTTWOWAYSTREAMREQUEST = DESCRIPTOR.message_types_by_name['TestTwoWayStreamRequest']
_TESTTWOWAYSTREAMRESPONSE = DESCRIPTOR.message_types_by_name['TestTwoWayStreamResponse']
HelloDeweiReq = _reflection.GeneratedProtocolMessageType('HelloDeweiReq', (_message.Message,), {
  'DESCRIPTOR' : _HELLODEWEIREQ,
  '__module__' : 'hello_bili_pb2'
  # @@protoc_insertion_point(class_scope:test.HelloDeweiReq)
  })
_sym_db.RegisterMessage(HelloDeweiReq)

HelloDeweiReply = _reflection.GeneratedProtocolMessageType('HelloDeweiReply', (_message.Message,), {
  'DESCRIPTOR' : _HELLODEWEIREPLY,
  '__module__' : 'hello_bili_pb2'
  # @@protoc_insertion_point(class_scope:test.HelloDeweiReply)
  })
_sym_db.RegisterMessage(HelloDeweiReply)

HelloTestRequest = _reflection.GeneratedProtocolMessageType('HelloTestRequest', (_message.Message,), {

  'HelloTestRequestNumberValue' : _reflection.GeneratedProtocolMessageType('HelloTestRequestNumberValue', (_message.Message,), {
    'DESCRIPTOR' : _HELLOTESTREQUEST_HELLOTESTREQUESTNUMBERVALUE,
    '__module__' : 'hello_bili_pb2'
    # @@protoc_insertion_point(class_scope:test.HelloTestRequest.HelloTestRequestNumberValue)
    })
  ,

  'NumberEntry' : _reflection.GeneratedProtocolMessageType('NumberEntry', (_message.Message,), {
    'DESCRIPTOR' : _HELLOTESTREQUEST_NUMBERENTRY,
    '__module__' : 'hello_bili_pb2'
    # @@protoc_insertion_point(class_scope:test.HelloTestRequest.NumberEntry)
    })
  ,
  'DESCRIPTOR' : _HELLOTESTREQUEST,
  '__module__' : 'hello_bili_pb2'
  # @@protoc_insertion_point(class_scope:test.HelloTestRequest)
  })
_sym_db.RegisterMessage(HelloTestRequest)
_sym_db.RegisterMessage(HelloTestRequest.HelloTestRequestNumberValue)
_sym_db.RegisterMessage(HelloTestRequest.NumberEntry)

HelloTestResponse = _reflection.GeneratedProtocolMessageType('HelloTestResponse', (_message.Message,), {
  'DESCRIPTOR' : _HELLOTESTRESPONSE,
  '__module__' : 'hello_bili_pb2'
  # @@protoc_insertion_point(class_scope:test.HelloTestResponse)
  })
_sym_db.RegisterMessage(HelloTestResponse)

TestClientRecvStreamRequest = _reflection.GeneratedProtocolMessageType('TestClientRecvStreamRequest', (_message.Message,), {
  'DESCRIPTOR' : _TESTCLIENTRECVSTREAMREQUEST,
  '__module__' : 'hello_bili_pb2'
  # @@protoc_insertion_point(class_scope:test.TestClientRecvStreamRequest)
  })
_sym_db.RegisterMessage(TestClientRecvStreamRequest)

TestClientRecvStreamResponse = _reflection.GeneratedProtocolMessageType('TestClientRecvStreamResponse', (_message.Message,), {
  'DESCRIPTOR' : _TESTCLIENTRECVSTREAMRESPONSE,
  '__module__' : 'hello_bili_pb2'
  # @@protoc_insertion_point(class_scope:test.TestClientRecvStreamResponse)
  })
_sym_db.RegisterMessage(TestClientRecvStreamResponse)

TestClientSendStreamRequest = _reflection.GeneratedProtocolMessageType('TestClientSendStreamRequest', (_message.Message,), {
  'DESCRIPTOR' : _TESTCLIENTSENDSTREAMREQUEST,
  '__module__' : 'hello_bili_pb2'
  # @@protoc_insertion_point(class_scope:test.TestClientSendStreamRequest)
  })
_sym_db.RegisterMessage(TestClientSendStreamRequest)

TestClientSendStreamResponse = _reflection.GeneratedProtocolMessageType('TestClientSendStreamResponse', (_message.Message,), {
  'DESCRIPTOR' : _TESTCLIENTSENDSTREAMRESPONSE,
  '__module__' : 'hello_bili_pb2'
  # @@protoc_insertion_point(class_scope:test.TestClientSendStreamResponse)
  })
_sym_db.RegisterMessage(TestClientSendStreamResponse)

TestTwoWayStreamRequest = _reflection.GeneratedProtocolMessageType('TestTwoWayStreamRequest', (_message.Message,), {
  'DESCRIPTOR' : _TESTTWOWAYSTREAMREQUEST,
  '__module__' : 'hello_bili_pb2'
  # @@protoc_insertion_point(class_scope:test.TestTwoWayStreamRequest)
  })
_sym_db.RegisterMessage(TestTwoWayStreamRequest)

TestTwoWayStreamResponse = _reflection.GeneratedProtocolMessageType('TestTwoWayStreamResponse', (_message.Message,), {
  'DESCRIPTOR' : _TESTTWOWAYSTREAMRESPONSE,
  '__module__' : 'hello_bili_pb2'
  # @@protoc_insertion_point(class_scope:test.TestTwoWayStreamResponse)
  })
_sym_db.RegisterMessage(TestTwoWayStreamResponse)

_BILI = DESCRIPTOR.services_by_name['Bili']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _HELLOTESTREQUEST_NUMBERENTRY._options = None
  _HELLOTESTREQUEST_NUMBERENTRY._serialized_options = b'8\001'
  _HELLODEWEIREQ._serialized_start=26
  _HELLODEWEIREQ._serialized_end=68
  _HELLODEWEIREPLY._serialized_start=70
  _HELLODEWEIREPLY._serialized_end=103
  _HELLOTESTREQUEST._serialized_start=106
  _HELLOTESTREQUEST._serialized_end=393
  _HELLOTESTREQUEST_HELLOTESTREQUESTNUMBERVALUE._serialized_start=219
  _HELLOTESTREQUEST_HELLOTESTREQUESTNUMBERVALUE._serialized_end=294
  _HELLOTESTREQUEST_NUMBERENTRY._serialized_start=296
  _HELLOTESTREQUEST_NUMBERENTRY._serialized_end=393
  _HELLOTESTRESPONSE._serialized_start=395
  _HELLOTESTRESPONSE._serialized_end=414
  _TESTCLIENTRECVSTREAMREQUEST._serialized_start=416
  _TESTCLIENTRECVSTREAMREQUEST._serialized_end=459
  _TESTCLIENTRECVSTREAMRESPONSE._serialized_start=461
  _TESTCLIENTRECVSTREAMRESPONSE._serialized_end=507
  _TESTCLIENTSENDSTREAMREQUEST._serialized_start=509
  _TESTCLIENTSENDSTREAMREQUEST._serialized_end=552
  _TESTCLIENTSENDSTREAMRESPONSE._serialized_start=554
  _TESTCLIENTSENDSTREAMRESPONSE._serialized_end=600
  _TESTTWOWAYSTREAMREQUEST._serialized_start=602
  _TESTTWOWAYSTREAMREQUEST._serialized_end=641
  _TESTTWOWAYSTREAMRESPONSE._serialized_start=643
  _TESTTWOWAYSTREAMRESPONSE._serialized_end=685
  _BILI._serialized_start=688
  _BILI._serialized_end=1109
# @@protoc_insertion_point(module_scope)
