# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: eos_utils.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x65os_utils.proto\x12\x16\x63om.mycompany.eosutils\"\x1f\n\x0c\x46\x65tchRequest\x12\x0f\n\x07\x61\x64\x64ress\x18\x01 \x01(\t\"6\n\nFetchReply\x12\x17\n\x0f\x62\x61lance_photons\x18\x01 \x01(\x04\x12\x0f\n\x07\x61\x64\x64ress\x18\x02 \x01(\t2g\n\tBlockInfo\x12Z\n\x0e\x46\x65tchBlockInfo\x12$.com.mycompany.eosutils.FetchRequest\x1a\".com.mycompany.eosutils.FetchReplyb\x06proto3')



_FETCHREQUEST = DESCRIPTOR.message_types_by_name['FetchRequest']
_FETCHREPLY = DESCRIPTOR.message_types_by_name['FetchReply']
FetchRequest = _reflection.GeneratedProtocolMessageType('FetchRequest', (_message.Message,), {
  'DESCRIPTOR' : _FETCHREQUEST,
  '__module__' : 'eos_utils_pb2'
  # @@protoc_insertion_point(class_scope:com.mycompany.eosutils.FetchRequest)
  })
_sym_db.RegisterMessage(FetchRequest)

FetchReply = _reflection.GeneratedProtocolMessageType('FetchReply', (_message.Message,), {
  'DESCRIPTOR' : _FETCHREPLY,
  '__module__' : 'eos_utils_pb2'
  # @@protoc_insertion_point(class_scope:com.mycompany.eosutils.FetchReply)
  })
_sym_db.RegisterMessage(FetchReply)

_BLOCKINFO = DESCRIPTOR.services_by_name['BlockInfo']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _FETCHREQUEST._serialized_start=43
  _FETCHREQUEST._serialized_end=74
  _FETCHREPLY._serialized_start=76
  _FETCHREPLY._serialized_end=130
  _BLOCKINFO._serialized_start=132
  _BLOCKINFO._serialized_end=235
# @@protoc_insertion_point(module_scope)
