# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import eos_utils_pb2 as eos__utils__pb2


class BlockInfoStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.FetchBlockInfo = channel.unary_unary(
                '/com.mycompany.eosutils.BlockInfo/FetchBlockInfo',
                request_serializer=eos__utils__pb2.FetchRequest.SerializeToString,
                response_deserializer=eos__utils__pb2.FetchReply.FromString,
                )


class BlockInfoServicer(object):
    """Missing associated documentation comment in .proto file."""

    def FetchBlockInfo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BlockInfoServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'FetchBlockInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.FetchBlockInfo,
                    request_deserializer=eos__utils__pb2.FetchRequest.FromString,
                    response_serializer=eos__utils__pb2.FetchReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'com.mycompany.eosutils.BlockInfo', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class BlockInfo(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def FetchBlockInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/com.mycompany.eosutils.BlockInfo/FetchBlockInfo',
            eos__utils__pb2.FetchRequest.SerializeToString,
            eos__utils__pb2.FetchReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
